version: '3.1'

services:
  tasks_mongo:
    image: mongo
    container_name: tasks_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 8081:27017

